<div class="d-flex justify-content-center">
	<div class="col-lg-5 col-md-7 col-12">
		<h1 id="privacy-policy">Privacy Policy</h1>
		<p>Last updated: December 10, 2021</p>
		<p>
			This Privacy Policy describes Our policies and procedures on the collection, use and
			disclosure of Your information when You use the Service and tells You about Your privacy
			rights and how the law protects You.
		</p>
		<p>
			We use Your Personal data to provide and improve the Service. By using the Service, You agree
			to the collection and use of information in accordance with this Privacy Policy. This Privacy
			Policy has been created with the help of the <a
				href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
				>Privacy Policy Generator</a
			>.
		</p>
		<h1 id="interpretation-and-definitions">Interpretation and Definitions</h1>
		<h2 id="interpretation">Interpretation</h2>
		<p>
			The words of which the initial letter is capitalized have meanings defined under the following
			conditions. The following definitions shall have the same meaning regardless of whether they
			appear in singular or in plural.
		</p>
		<h2 id="definitions">Definitions</h2>
		<p>For the purposes of this Privacy Policy:</p>
		<ul>
			<li>
				<p>
					<strong>Account</strong> means a unique account created for You to access our Service or parts
					of our Service.
				</p>
			</li>
			<li>
				<p>
					<strong>Application</strong> means the software program provided by the Company downloaded
					by You on any electronic device, named Gradely 2
				</p>
			</li>
			<li>
				<p>
					<strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot;
					or &quot;Our&quot; in this Agreement) refers to Gradely 2.
				</p>
			</li>
			<li><p><strong>Country</strong> refers to: Switzerland</p></li>
			<li>
				<p>
					<strong>Device</strong> means any device that can access the Service such as a computer, a
					cellphone or a digital tablet.
				</p>
			</li>
			<li>
				<p>
					<strong>Personal Data</strong> is any information that relates to an identified or identifiable
					individual.
				</p>
			</li>
			<li><p><strong>Service</strong> refers to the Application.</p></li>
			<li>
				<p>
					<strong>Service Provider</strong> means any natural or legal person who processes the data
					on behalf of the Company. It refers to third-party companies or individuals employed by the
					Company to facilitate the Service, to provide the Service on behalf of the Company, to perform
					services related to the Service or to assist the Company in analyzing how the Service is used.
				</p>
			</li>
			<li>
				<p>
					<strong>Usage Data</strong> refers to data collected automatically, either generated by the
					use of the Service or from the Service infrastructure itself (for example, the duration of
					a page visit).
				</p>
			</li>
			<li>
				<p>
					<strong>You</strong> means the individual accessing or using the Service, or the company, or
					other legal entity on behalf of which such individual is accessing or using the Service, as
					applicable.
				</p>
			</li>
		</ul>
		<h1 id="collecting-and-using-your-personal-data">Collecting and Using Your Personal Data</h1>
		<h2 id="types-of-data-collected">Types of Data Collected</h2>
		<h3 id="personal-data">Personal Data</h3>
		<p>
			While using Our Service, We may ask You to provide Us with certain personally identifiable
			information that can be used to contact or identify You. Personally identifiable information
			may include, but is not limited to:
		</p>
		<ul>
			<li><p>Email address</p></li>
			<li><p>First name and last name</p></li>
			<li><p>Usage Data</p></li>
		</ul>
		<h3 id="usage-data">Usage Data</h3>
		<p>Usage Data is collected automatically when using the Service.</p>
		<p>
			Usage Data may include information such as Your Device&#39;s Internet Protocol address (e.g.
			IP address), browser type, browser version, the pages of our Service that You visit, the time
			and date of Your visit, the time spent on those pages, unique device identifiers and other
			diagnostic data.
		</p>
		<p>
			When You access the Service by or through a mobile device, We may collect certain information
			automatically, including, but not limited to, the type of mobile device You use, Your mobile
			device unique ID, the IP address of Your mobile device, Your mobile operating system, the type
			of mobile Internet browser You use, unique device identifiers and other diagnostic data.
		</p>
		<p>
			We may also collect information that Your browser sends whenever You visit our Service or when
			You access the Service by or through a mobile device.
		</p>
		<h2 id="use-of-your-personal-data">Use of Your Personal Data</h2>
		<p>The Company may use Personal Data for the following purposes:</p>
		<ul>
			<li>
				<p>
					<strong>To provide and maintain our Service</strong>, including to monitor the usage of
					our Service.
				</p>
			</li>
			<li>
				<p>
					<strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.
					The Personal Data You provide can give You access to different functionalities of the Service
					that are available to You as a registered user.
				</p>
			</li>
			<li>
				<p>
					<strong>For the performance of a contract:</strong> the development, compliance and undertaking
					of the purchase contract for the products, items or services You have purchased or of any other
					contract with Us through the Service.
				</p>
			</li>
			<li>
				<p>
					<strong>To contact You:</strong> To contact You by email or other equivalent forms of electronic
					communication, such as a mobile application&#39;s push notifications regarding updates or informative
					communications related to the functionalities, products or contracted services, including the
					security updates, when necessary or reasonable for their implementation.
				</p>
			</li>
			<li>
				<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
			</li>
		</ul>
		<ul>
			<li>
				<strong>For other purposes</strong>: We may use Your information for other purposes, such as
				data analysis, identifying usage trends, determining the effectiveness of our promotional
				campaigns and to evaluate and improve our Service, products, services, marketing and your
				experience.
			</li>
		</ul>
		<h2 id="retention-of-your-personal-data">Retention of Your Personal Data</h2>
		<p>
			The Company will retain Your Personal Data only for as long as is necessary for the purposes
			set out in this Privacy Policy. We will retain and use Your Personal Data to the extent
			necessary to comply with our legal obligations (for example, if we are required to retain your
			data to comply with applicable laws), resolve disputes, and enforce our legal agreements and
			policies.
		</p>
		<p>
			The Company will also retain Usage Data for internal analysis purposes. Usage Data is
			generally retained for a shorter period of time, except when this data is used to strengthen
			the security or to improve the functionality of Our Service, or We are legally obligated to
			retain this data for longer time periods.
		</p>
		<h2 id="disclosure-of-your-personal-data">Disclosure of Your Personal Data</h2>
		<h3 id="business-transactions">Business Transactions</h3>
		<p>
			If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
			transferred. We will provide notice before Your Personal Data is transferred and becomes
			subject to a different Privacy Policy.
		</p>
		<h3 id="law-enforcement">Law enforcement</h3>
		<p>
			Under certain circumstances, the Company may be required to disclose Your Personal Data if
			required to do so by law or in response to valid requests by public authorities (e.g. a court
			or a government agency).
		</p>
		<h3 id="other-legal-requirements">Other legal requirements</h3>
		<p>
			The Company may disclose Your Personal Data in the good faith belief that such action is
			necessary to:
		</p>
		<ul>
			<li>Comply with a legal obligation</li>
			<li>Protect and defend the rights or property of the Company</li>
			<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
			<li>Protect the personal safety of Users of the Service or the public</li>
			<li>Protect against legal liability</li>
		</ul>
		<h2 id="security-of-your-personal-data">Security of Your Personal Data</h2>
		<p>
			The security of Your Personal Data is important to Us, but remember that no method of
			transmission over the Internet, or method of electronic storage is 100% secure. While We
			strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee
			its absolute security.
		</p>
		<h1 id="changes-to-this-privacy-policy">Changes to this Privacy Policy</h1>
		<p>
			We may update Our Privacy Policy from time to time. We will notify You of any changes by
			posting the new Privacy Policy on this page.
		</p>
		<p>
			We will let You know via email and/or a prominent notice on Our Service, prior to the change
			becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy
			Policy.
		</p>
		<p>
			You are advised to review this Privacy Policy periodically for any changes. Changes to this
			Privacy Policy are effective when they are posted on this page.
		</p>
		<h1 id="contact-us">Contact Us</h1>
		<p>
			If you have any questions about this Privacy Policy, You can contact me by email:
			elias@eliasschneider.com
		</p>
	</div>
</div>

<style>
	h1,
	h2,
	h3 {
		font-family: Arial, Helvetica, sans-serif;
	}
</style>
